// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Capture/Capture.proto

package Capture

import (
	IdType "IdType"
	PFType "PFType"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EDirection_Enum int32

const (
	EDirection_kRx            EDirection_Enum = 0
	EDirection_kTx            EDirection_Enum = 1
	EDirection_kBidirectional EDirection_Enum = 2
)

var EDirection_Enum_name = map[int32]string{
	0: "kRx",
	1: "kTx",
	2: "kBidirectional",
}

var EDirection_Enum_value = map[string]int32{
	"kRx":            0,
	"kTx":            1,
	"kBidirectional": 2,
}

func (x EDirection_Enum) String() string {
	return proto.EnumName(EDirection_Enum_name, int32(x))
}

func (EDirection_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{14, 0}
}

type EPacketFormat_Enum int32

const (
	EPacketFormat_kRaw  EPacketFormat_Enum = 0
	EPacketFormat_kPcap EPacketFormat_Enum = 1
)

var EPacketFormat_Enum_name = map[int32]string{
	0: "kRaw",
	1: "kPcap",
}

var EPacketFormat_Enum_value = map[string]int32{
	"kRaw":  0,
	"kPcap": 1,
}

func (x EPacketFormat_Enum) String() string {
	return proto.EnumName(EPacketFormat_Enum_name, int32(x))
}

func (EPacketFormat_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{15, 0}
}

type ETimestampPrecision_Enum int32

const (
	ETimestampPrecision_kMicroSec ETimestampPrecision_Enum = 0
	ETimestampPrecision_kNanoSec  ETimestampPrecision_Enum = 1
)

var ETimestampPrecision_Enum_name = map[int32]string{
	0: "kMicroSec",
	1: "kNanoSec",
}

var ETimestampPrecision_Enum_value = map[string]int32{
	"kMicroSec": 0,
	"kNanoSec":  1,
}

func (x ETimestampPrecision_Enum) String() string {
	return proto.EnumName(ETimestampPrecision_Enum_name, int32(x))
}

func (ETimestampPrecision_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{16, 0}
}

type EPatternKind_Enum int32

const (
	EPatternKind_kSrcAddrPattern EPatternKind_Enum = 0
	EPatternKind_kDstAddrPattern EPatternKind_Enum = 1
	EPatternKind_kDataPattern    EPatternKind_Enum = 2
	EPatternKind_kQoSPattern     EPatternKind_Enum = 3
)

var EPatternKind_Enum_name = map[int32]string{
	0: "kSrcAddrPattern",
	1: "kDstAddrPattern",
	2: "kDataPattern",
	3: "kQoSPattern",
}

var EPatternKind_Enum_value = map[string]int32{
	"kSrcAddrPattern": 0,
	"kDstAddrPattern": 1,
	"kDataPattern":    2,
	"kQoSPattern":     3,
}

func (x EPatternKind_Enum) String() string {
	return proto.EnumName(EPatternKind_Enum_name, int32(x))
}

func (EPatternKind_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{17, 0}
}

type EExpressionKind_Enum int32

const (
	EExpressionKind_kUds     EExpressionKind_Enum = 0
	EExpressionKind_kTrigger EExpressionKind_Enum = 1
	EExpressionKind_kFilter  EExpressionKind_Enum = 2
)

var EExpressionKind_Enum_name = map[int32]string{
	0: "kUds",
	1: "kTrigger",
	2: "kFilter",
}

var EExpressionKind_Enum_value = map[string]int32{
	"kUds":     0,
	"kTrigger": 1,
	"kFilter":  2,
}

func (x EExpressionKind_Enum) String() string {
	return proto.EnumName(EExpressionKind_Enum_name, int32(x))
}

func (EExpressionKind_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{18, 0}
}

type EAfterTriggerFilter_Enum int32

const (
	EAfterTriggerFilter_kCaptureAll       EAfterTriggerFilter_Enum = 0
	EAfterTriggerFilter_kUseTriggerFilter EAfterTriggerFilter_Enum = 1
	EAfterTriggerFilter_kUseCaptureFilter EAfterTriggerFilter_Enum = 2
)

var EAfterTriggerFilter_Enum_name = map[int32]string{
	0: "kCaptureAll",
	1: "kUseTriggerFilter",
	2: "kUseCaptureFilter",
}

var EAfterTriggerFilter_Enum_value = map[string]int32{
	"kCaptureAll":       0,
	"kUseTriggerFilter": 1,
	"kUseCaptureFilter": 2,
}

func (x EAfterTriggerFilter_Enum) String() string {
	return proto.EnumName(EAfterTriggerFilter_Enum_name, int32(x))
}

func (EAfterTriggerFilter_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{19, 0}
}

type EBeforeTriggerFilter_Enum int32

const (
	EBeforeTriggerFilter_kCaptureAll       EBeforeTriggerFilter_Enum = 0
	EBeforeTriggerFilter_kCaptureNone      EBeforeTriggerFilter_Enum = 1
	EBeforeTriggerFilter_kUseCaptureFilter EBeforeTriggerFilter_Enum = 2
)

var EBeforeTriggerFilter_Enum_name = map[int32]string{
	0: "kCaptureAll",
	1: "kCaptureNone",
	2: "kUseCaptureFilter",
}

var EBeforeTriggerFilter_Enum_value = map[string]int32{
	"kCaptureAll":       0,
	"kCaptureNone":      1,
	"kUseCaptureFilter": 2,
}

func (x EBeforeTriggerFilter_Enum) String() string {
	return proto.EnumName(EBeforeTriggerFilter_Enum_name, int32(x))
}

func (EBeforeTriggerFilter_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{20, 0}
}

type EContinuousFilter_Enum int32

const (
	EContinuousFilter_kCaptureAll       EContinuousFilter_Enum = 0
	EContinuousFilter_kUseCaptureFilter EContinuousFilter_Enum = 1
)

var EContinuousFilter_Enum_name = map[int32]string{
	0: "kCaptureAll",
	1: "kUseCaptureFilter",
}

var EContinuousFilter_Enum_value = map[string]int32{
	"kCaptureAll":       0,
	"kUseCaptureFilter": 1,
}

func (x EContinuousFilter_Enum) String() string {
	return proto.EnumName(EContinuousFilter_Enum_name, int32(x))
}

func (EContinuousFilter_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{21, 0}
}

type ECaptureMode_Enum int32

const (
	ECaptureMode_kContinuousMode ECaptureMode_Enum = 0
	ECaptureMode_kTriggerMode    ECaptureMode_Enum = 1
)

var ECaptureMode_Enum_name = map[int32]string{
	0: "kContinuousMode",
	1: "kTriggerMode",
}

var ECaptureMode_Enum_value = map[string]int32{
	"kContinuousMode": 0,
	"kTriggerMode":    1,
}

func (x ECaptureMode_Enum) String() string {
	return proto.EnumName(ECaptureMode_Enum_name, int32(x))
}

func (ECaptureMode_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{22, 0}
}

type ECaptureState_Enum int32

const (
	ECaptureState_kCaptureStopped ECaptureState_Enum = 0
	ECaptureState_kCaptureStarted ECaptureState_Enum = 1
)

var ECaptureState_Enum_name = map[int32]string{
	0: "kCaptureStopped",
	1: "kCaptureStarted",
}

var ECaptureState_Enum_value = map[string]int32{
	"kCaptureStopped": 0,
	"kCaptureStarted": 1,
}

func (x ECaptureState_Enum) String() string {
	return proto.EnumName(ECaptureState_Enum_name, int32(x))
}

func (ECaptureState_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{23, 0}
}

type EAnchor_Enum int32

const (
	EAnchor_kStartOfFrame    EAnchor_Enum = 0
	EAnchor_kStartOfIP       EAnchor_Enum = 1
	EAnchor_kStartOfProtocol EAnchor_Enum = 2
)

var EAnchor_Enum_name = map[int32]string{
	0: "kStartOfFrame",
	1: "kStartOfIP",
	2: "kStartOfProtocol",
}

var EAnchor_Enum_value = map[string]int32{
	"kStartOfFrame":    0,
	"kStartOfIP":       1,
	"kStartOfProtocol": 2,
}

func (x EAnchor_Enum) String() string {
	return proto.EnumName(EAnchor_Enum_name, int32(x))
}

func (EAnchor_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{24, 0}
}

type ELogic_Enum int32

const (
	ELogic_kNotPattern  ELogic_Enum = 0
	ELogic_kAndPattern  ELogic_Enum = 1
	ELogic_kOrPattern   ELogic_Enum = 2
	ELogic_kXorPattern  ELogic_Enum = 3
	ELogic_kNandPattern ELogic_Enum = 4
	ELogic_kNorPattern  ELogic_Enum = 5
)

var ELogic_Enum_name = map[int32]string{
	0: "kNotPattern",
	1: "kAndPattern",
	2: "kOrPattern",
	3: "kXorPattern",
	4: "kNandPattern",
	5: "kNorPattern",
}

var ELogic_Enum_value = map[string]int32{
	"kNotPattern":  0,
	"kAndPattern":  1,
	"kOrPattern":   2,
	"kXorPattern":  3,
	"kNandPattern": 4,
	"kNorPattern":  5,
}

func (x ELogic_Enum) String() string {
	return proto.EnumName(ELogic_Enum_name, int32(x))
}

func (ELogic_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{25, 0}
}

type EErrorMatch_Enum int32

const (
	EErrorMatch_kAnyFrame                    EErrorMatch_Enum = 0
	EErrorMatch_kErrGoodFrame                EErrorMatch_Enum = 1
	EErrorMatch_kErrBadCRC                   EErrorMatch_Enum = 2
	EErrorMatch_kErrBadFrame                 EErrorMatch_Enum = 3
	EErrorMatch_kErrAnySequenceError         EErrorMatch_Enum = 4
	EErrorMatch_kErrSmallSequenceError       EErrorMatch_Enum = 5
	EErrorMatch_kErrBigSequenceError         EErrorMatch_Enum = 6
	EErrorMatch_kErrReverseSequenceError     EErrorMatch_Enum = 7
	EErrorMatch_kErrDataIntegrityError       EErrorMatch_Enum = 8
	EErrorMatch_kErrAnyIpTcpUdpChecksumError EErrorMatch_Enum = 9
	EErrorMatch_kErrReverseDuplicatePacket   EErrorMatch_Enum = 10
	EErrorMatch_kErrSequenceGap              EErrorMatch_Enum = 11
	EErrorMatch_kErrCdlErrors                EErrorMatch_Enum = 12
	EErrorMatch_kErrFCoEInvalidFrame         EErrorMatch_Enum = 13
)

var EErrorMatch_Enum_name = map[int32]string{
	0:  "kAnyFrame",
	1:  "kErrGoodFrame",
	2:  "kErrBadCRC",
	3:  "kErrBadFrame",
	4:  "kErrAnySequenceError",
	5:  "kErrSmallSequenceError",
	6:  "kErrBigSequenceError",
	7:  "kErrReverseSequenceError",
	8:  "kErrDataIntegrityError",
	9:  "kErrAnyIpTcpUdpChecksumError",
	10: "kErrReverseDuplicatePacket",
	11: "kErrSequenceGap",
	12: "kErrCdlErrors",
	13: "kErrFCoEInvalidFrame",
}

var EErrorMatch_Enum_value = map[string]int32{
	"kAnyFrame":                    0,
	"kErrGoodFrame":                1,
	"kErrBadCRC":                   2,
	"kErrBadFrame":                 3,
	"kErrAnySequenceError":         4,
	"kErrSmallSequenceError":       5,
	"kErrBigSequenceError":         6,
	"kErrReverseSequenceError":     7,
	"kErrDataIntegrityError":       8,
	"kErrAnyIpTcpUdpChecksumError": 9,
	"kErrReverseDuplicatePacket":   10,
	"kErrSequenceGap":              11,
	"kErrCdlErrors":                12,
	"kErrFCoEInvalidFrame":         13,
}

func (x EErrorMatch_Enum) String() string {
	return proto.EnumName(EErrorMatch_Enum_name, int32(x))
}

func (EErrorMatch_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{26, 0}
}

type ECircuitList_Enum int32

const (
	ECircuitList_kAnyCircuit  ECircuitList_Enum = 0
	ECircuitList_kCircuitList ECircuitList_Enum = 1
)

var ECircuitList_Enum_name = map[int32]string{
	0: "kAnyCircuit",
	1: "kCircuitList",
}

var ECircuitList_Enum_value = map[string]int32{
	"kAnyCircuit":  0,
	"kCircuitList": 1,
}

func (x ECircuitList_Enum) String() string {
	return proto.EnumName(ECircuitList_Enum_name, int32(x))
}

func (ECircuitList_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{27, 0}
}

type EExpressionElementKind_Enum int32

const (
	EExpressionElementKind_kOperator EExpressionElementKind_Enum = 0
	EExpressionElementKind_kPattern  EExpressionElementKind_Enum = 1
)

var EExpressionElementKind_Enum_name = map[int32]string{
	0: "kOperator",
	1: "kPattern",
}

var EExpressionElementKind_Enum_value = map[string]int32{
	"kOperator": 0,
	"kPattern":  1,
}

func (x EExpressionElementKind_Enum) String() string {
	return proto.EnumName(EExpressionElementKind_Enum_name, int32(x))
}

func (EExpressionElementKind_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{28, 0}
}

type EFilterExpressionParserType_Enum int32

const (
	EFilterExpressionParserType_kSimpleExpressionParser  EFilterExpressionParserType_Enum = 0
	EFilterExpressionParserType_kComplexExpressionParser EFilterExpressionParserType_Enum = 1
	EFilterExpressionParserType_kTokaidoExpressionParser EFilterExpressionParserType_Enum = 2
)

var EFilterExpressionParserType_Enum_name = map[int32]string{
	0: "kSimpleExpressionParser",
	1: "kComplexExpressionParser",
	2: "kTokaidoExpressionParser",
}

var EFilterExpressionParserType_Enum_value = map[string]int32{
	"kSimpleExpressionParser":  0,
	"kComplexExpressionParser": 1,
	"kTokaidoExpressionParser": 2,
}

func (x EFilterExpressionParserType_Enum) String() string {
	return proto.EnumName(EFilterExpressionParserType_Enum_name, int32(x))
}

func (EFilterExpressionParserType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{29, 0}
}

type ERXSharedStats_Enum int32

const (
	ERXSharedStats_kInvalidDelimiter    ERXSharedStats_Enum = 0
	ERXSharedStats_kInvalidFrames       ERXSharedStats_Enum = 1
	ERXSharedStats_kInvalidSize         ERXSharedStats_Enum = 2
	ERXSharedStats_kNormalSizeBadFCCRC  ERXSharedStats_Enum = 3
	ERXSharedStats_kNormalSizeGoodFCCRC ERXSharedStats_Enum = 4
	ERXSharedStats_kUndersizeBadFCCRC   ERXSharedStats_Enum = 5
	ERXSharedStats_kUndersizeGoodFCCRC  ERXSharedStats_Enum = 6
	ERXSharedStats_kValidFrames         ERXSharedStats_Enum = 7
)

var ERXSharedStats_Enum_name = map[int32]string{
	0: "kInvalidDelimiter",
	1: "kInvalidFrames",
	2: "kInvalidSize",
	3: "kNormalSizeBadFCCRC",
	4: "kNormalSizeGoodFCCRC",
	5: "kUndersizeBadFCCRC",
	6: "kUndersizeGoodFCCRC",
	7: "kValidFrames",
}

var ERXSharedStats_Enum_value = map[string]int32{
	"kInvalidDelimiter":    0,
	"kInvalidFrames":       1,
	"kInvalidSize":         2,
	"kNormalSizeBadFCCRC":  3,
	"kNormalSizeGoodFCCRC": 4,
	"kUndersizeBadFCCRC":   5,
	"kUndersizeGoodFCCRC":  6,
	"kValidFrames":         7,
}

func (x ERXSharedStats_Enum) String() string {
	return proto.EnumName(ERXSharedStats_Enum_name, int32(x))
}

func (ERXSharedStats_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{30, 0}
}

type QoSPatternType struct {
	QosByteOffset        int32    `protobuf:"varint,1,opt,name=qosByteOffset,proto3" json:"qosByteOffset,omitempty"`
	Anchor               *EAnchor `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Pattern              uint32   `protobuf:"varint,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Select               uint32   `protobuf:"varint,5,opt,name=select,proto3" json:"select,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QoSPatternType) Reset()         { *m = QoSPatternType{} }
func (m *QoSPatternType) String() string { return proto.CompactTextString(m) }
func (*QoSPatternType) ProtoMessage()    {}
func (*QoSPatternType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{0}
}

func (m *QoSPatternType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QoSPatternType.Unmarshal(m, b)
}
func (m *QoSPatternType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QoSPatternType.Marshal(b, m, deterministic)
}
func (m *QoSPatternType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QoSPatternType.Merge(m, src)
}
func (m *QoSPatternType) XXX_Size() int {
	return xxx_messageInfo_QoSPatternType.Size(m)
}
func (m *QoSPatternType) XXX_DiscardUnknown() {
	xxx_messageInfo_QoSPatternType.DiscardUnknown(m)
}

var xxx_messageInfo_QoSPatternType proto.InternalMessageInfo

func (m *QoSPatternType) GetQosByteOffset() int32 {
	if m != nil {
		return m.QosByteOffset
	}
	return 0
}

func (m *QoSPatternType) GetAnchor() *EAnchor {
	if m != nil {
		return m.Anchor
	}
	return nil
}

func (m *QoSPatternType) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QoSPatternType) GetPattern() uint32 {
	if m != nil {
		return m.Pattern
	}
	return 0
}

func (m *QoSPatternType) GetSelect() uint32 {
	if m != nil {
		return m.Select
	}
	return 0
}

type DataPatternType struct {
	Anchor               *EAnchor `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Pattern              uint32   `protobuf:"varint,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Select               uint32   `protobuf:"varint,4,opt,name=select,proto3" json:"select,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataPatternType) Reset()         { *m = DataPatternType{} }
func (m *DataPatternType) String() string { return proto.CompactTextString(m) }
func (*DataPatternType) ProtoMessage()    {}
func (*DataPatternType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{1}
}

func (m *DataPatternType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPatternType.Unmarshal(m, b)
}
func (m *DataPatternType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPatternType.Marshal(b, m, deterministic)
}
func (m *DataPatternType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPatternType.Merge(m, src)
}
func (m *DataPatternType) XXX_Size() int {
	return xxx_messageInfo_DataPatternType.Size(m)
}
func (m *DataPatternType) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPatternType.DiscardUnknown(m)
}

var xxx_messageInfo_DataPatternType proto.InternalMessageInfo

func (m *DataPatternType) GetAnchor() *EAnchor {
	if m != nil {
		return m.Anchor
	}
	return nil
}

func (m *DataPatternType) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DataPatternType) GetPattern() uint32 {
	if m != nil {
		return m.Pattern
	}
	return 0
}

func (m *DataPatternType) GetSelect() uint32 {
	if m != nil {
		return m.Select
	}
	return 0
}

type MacPatternType struct {
	Address              *PFType.MacAddressType `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Select               *PFType.MacAddressType `protobuf:"bytes,2,opt,name=select,proto3" json:"select,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MacPatternType) Reset()         { *m = MacPatternType{} }
func (m *MacPatternType) String() string { return proto.CompactTextString(m) }
func (*MacPatternType) ProtoMessage()    {}
func (*MacPatternType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{2}
}

func (m *MacPatternType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MacPatternType.Unmarshal(m, b)
}
func (m *MacPatternType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MacPatternType.Marshal(b, m, deterministic)
}
func (m *MacPatternType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MacPatternType.Merge(m, src)
}
func (m *MacPatternType) XXX_Size() int {
	return xxx_messageInfo_MacPatternType.Size(m)
}
func (m *MacPatternType) XXX_DiscardUnknown() {
	xxx_messageInfo_MacPatternType.DiscardUnknown(m)
}

var xxx_messageInfo_MacPatternType proto.InternalMessageInfo

func (m *MacPatternType) GetAddress() *PFType.MacAddressType {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MacPatternType) GetSelect() *PFType.MacAddressType {
	if m != nil {
		return m.Select
	}
	return nil
}

type PatternType struct {
	PatternId            *IdType.CapturePatternId `protobuf:"bytes,1,opt,name=patternId,proto3" json:"patternId,omitempty"`
	PatternKind          *EPatternKind            `protobuf:"bytes,2,opt,name=patternKind,proto3" json:"patternKind,omitempty"`
	SrcAddrPattern       *MacPatternType          `protobuf:"bytes,3,opt,name=srcAddrPattern,proto3" json:"srcAddrPattern,omitempty"`
	DstAddrPattern       *MacPatternType          `protobuf:"bytes,4,opt,name=dstAddrPattern,proto3" json:"dstAddrPattern,omitempty"`
	DataPattern          *DataPatternType         `protobuf:"bytes,5,opt,name=dataPattern,proto3" json:"dataPattern,omitempty"`
	QosPattern           *QoSPatternType          `protobuf:"bytes,6,opt,name=qosPattern,proto3" json:"qosPattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PatternType) Reset()         { *m = PatternType{} }
func (m *PatternType) String() string { return proto.CompactTextString(m) }
func (*PatternType) ProtoMessage()    {}
func (*PatternType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{3}
}

func (m *PatternType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatternType.Unmarshal(m, b)
}
func (m *PatternType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatternType.Marshal(b, m, deterministic)
}
func (m *PatternType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatternType.Merge(m, src)
}
func (m *PatternType) XXX_Size() int {
	return xxx_messageInfo_PatternType.Size(m)
}
func (m *PatternType) XXX_DiscardUnknown() {
	xxx_messageInfo_PatternType.DiscardUnknown(m)
}

var xxx_messageInfo_PatternType proto.InternalMessageInfo

func (m *PatternType) GetPatternId() *IdType.CapturePatternId {
	if m != nil {
		return m.PatternId
	}
	return nil
}

func (m *PatternType) GetPatternKind() *EPatternKind {
	if m != nil {
		return m.PatternKind
	}
	return nil
}

func (m *PatternType) GetSrcAddrPattern() *MacPatternType {
	if m != nil {
		return m.SrcAddrPattern
	}
	return nil
}

func (m *PatternType) GetDstAddrPattern() *MacPatternType {
	if m != nil {
		return m.DstAddrPattern
	}
	return nil
}

func (m *PatternType) GetDataPattern() *DataPatternType {
	if m != nil {
		return m.DataPattern
	}
	return nil
}

func (m *PatternType) GetQosPattern() *QoSPatternType {
	if m != nil {
		return m.QosPattern
	}
	return nil
}

type FrameSizeRangeType struct {
	IsEnabled            bool     `protobuf:"varint,1,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	IsInRange            bool     `protobuf:"varint,2,opt,name=isInRange,proto3" json:"isInRange,omitempty"`
	From                 int32    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameSizeRangeType) Reset()         { *m = FrameSizeRangeType{} }
func (m *FrameSizeRangeType) String() string { return proto.CompactTextString(m) }
func (*FrameSizeRangeType) ProtoMessage()    {}
func (*FrameSizeRangeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{4}
}

func (m *FrameSizeRangeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameSizeRangeType.Unmarshal(m, b)
}
func (m *FrameSizeRangeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameSizeRangeType.Marshal(b, m, deterministic)
}
func (m *FrameSizeRangeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameSizeRangeType.Merge(m, src)
}
func (m *FrameSizeRangeType) XXX_Size() int {
	return xxx_messageInfo_FrameSizeRangeType.Size(m)
}
func (m *FrameSizeRangeType) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameSizeRangeType.DiscardUnknown(m)
}

var xxx_messageInfo_FrameSizeRangeType proto.InternalMessageInfo

func (m *FrameSizeRangeType) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *FrameSizeRangeType) GetIsInRange() bool {
	if m != nil {
		return m.IsInRange
	}
	return false
}

func (m *FrameSizeRangeType) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *FrameSizeRangeType) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type ExpressionElementType struct {
	ElementKind          *EExpressionElementKind  `protobuf:"bytes,1,opt,name=elementKind,proto3" json:"elementKind,omitempty"`
	OperatorLogic        *ELogic                  `protobuf:"bytes,2,opt,name=operatorLogic,proto3" json:"operatorLogic,omitempty"`
	PatternId            *IdType.CapturePatternId `protobuf:"bytes,3,opt,name=patternId,proto3" json:"patternId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ExpressionElementType) Reset()         { *m = ExpressionElementType{} }
func (m *ExpressionElementType) String() string { return proto.CompactTextString(m) }
func (*ExpressionElementType) ProtoMessage()    {}
func (*ExpressionElementType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{5}
}

func (m *ExpressionElementType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionElementType.Unmarshal(m, b)
}
func (m *ExpressionElementType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionElementType.Marshal(b, m, deterministic)
}
func (m *ExpressionElementType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionElementType.Merge(m, src)
}
func (m *ExpressionElementType) XXX_Size() int {
	return xxx_messageInfo_ExpressionElementType.Size(m)
}
func (m *ExpressionElementType) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionElementType.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionElementType proto.InternalMessageInfo

func (m *ExpressionElementType) GetElementKind() *EExpressionElementKind {
	if m != nil {
		return m.ElementKind
	}
	return nil
}

func (m *ExpressionElementType) GetOperatorLogic() *ELogic {
	if m != nil {
		return m.OperatorLogic
	}
	return nil
}

func (m *ExpressionElementType) GetPatternId() *IdType.CapturePatternId {
	if m != nil {
		return m.PatternId
	}
	return nil
}

type ExpressionType struct {
	ExpressionKind          *EExpressionKind             `protobuf:"bytes,1,opt,name=expressionKind,proto3" json:"expressionKind,omitempty"`
	ErrorMatch              *EErrorMatch                 `protobuf:"bytes,2,opt,name=errorMatch,proto3" json:"errorMatch,omitempty"`
	FrameSizeRange          *FrameSizeRangeType          `protobuf:"bytes,3,opt,name=frameSizeRange,proto3" json:"frameSizeRange,omitempty"`
	SonetCircuitList        *ECircuitList                `protobuf:"bytes,4,opt,name=sonetCircuitList,proto3" json:"sonetCircuitList,omitempty"`
	FilterContent           *ExpressionContent           `protobuf:"bytes,5,opt,name=filterContent,proto3" json:"filterContent,omitempty"`
	IsExpressionEnabled     bool                         `protobuf:"varint,6,opt,name=isExpressionEnabled,proto3" json:"isExpressionEnabled,omitempty"`
	FilterExpressionContent *ExpressionContent           `protobuf:"bytes,7,opt,name=filterExpressionContent,proto3" json:"filterExpressionContent,omitempty"`
	ExpressionParserType    *EFilterExpressionParserType `protobuf:"bytes,8,opt,name=expressionParserType,proto3" json:"expressionParserType,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                     `json:"-"`
	XXX_unrecognized        []byte                       `json:"-"`
	XXX_sizecache           int32                        `json:"-"`
}

func (m *ExpressionType) Reset()         { *m = ExpressionType{} }
func (m *ExpressionType) String() string { return proto.CompactTextString(m) }
func (*ExpressionType) ProtoMessage()    {}
func (*ExpressionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{6}
}

func (m *ExpressionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionType.Unmarshal(m, b)
}
func (m *ExpressionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionType.Marshal(b, m, deterministic)
}
func (m *ExpressionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionType.Merge(m, src)
}
func (m *ExpressionType) XXX_Size() int {
	return xxx_messageInfo_ExpressionType.Size(m)
}
func (m *ExpressionType) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionType.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionType proto.InternalMessageInfo

func (m *ExpressionType) GetExpressionKind() *EExpressionKind {
	if m != nil {
		return m.ExpressionKind
	}
	return nil
}

func (m *ExpressionType) GetErrorMatch() *EErrorMatch {
	if m != nil {
		return m.ErrorMatch
	}
	return nil
}

func (m *ExpressionType) GetFrameSizeRange() *FrameSizeRangeType {
	if m != nil {
		return m.FrameSizeRange
	}
	return nil
}

func (m *ExpressionType) GetSonetCircuitList() *ECircuitList {
	if m != nil {
		return m.SonetCircuitList
	}
	return nil
}

func (m *ExpressionType) GetFilterContent() *ExpressionContent {
	if m != nil {
		return m.FilterContent
	}
	return nil
}

func (m *ExpressionType) GetIsExpressionEnabled() bool {
	if m != nil {
		return m.IsExpressionEnabled
	}
	return false
}

func (m *ExpressionType) GetFilterExpressionContent() *ExpressionContent {
	if m != nil {
		return m.FilterExpressionContent
	}
	return nil
}

func (m *ExpressionType) GetExpressionParserType() *EFilterExpressionParserType {
	if m != nil {
		return m.ExpressionParserType
	}
	return nil
}

type SettingsType struct {
	CaptureMode          *ECaptureMode         `protobuf:"bytes,1,opt,name=captureMode,proto3" json:"captureMode,omitempty"`
	AfterTriggerFilter   *EAfterTriggerFilter  `protobuf:"bytes,2,opt,name=afterTriggerFilter,proto3" json:"afterTriggerFilter,omitempty"`
	BeforeTriggerFilter  *EBeforeTriggerFilter `protobuf:"bytes,3,opt,name=beforeTriggerFilter,proto3" json:"beforeTriggerFilter,omitempty"`
	ContinuousFilter     *EContinuousFilter    `protobuf:"bytes,4,opt,name=continuousFilter,proto3" json:"continuousFilter,omitempty"`
	SliceSize            int32                 `protobuf:"varint,5,opt,name=sliceSize,proto3" json:"sliceSize,omitempty"`
	TriggerPosition      *PFType.KBType        `protobuf:"bytes,6,opt,name=triggerPosition,proto3" json:"triggerPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SettingsType) Reset()         { *m = SettingsType{} }
func (m *SettingsType) String() string { return proto.CompactTextString(m) }
func (*SettingsType) ProtoMessage()    {}
func (*SettingsType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{7}
}

func (m *SettingsType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsType.Unmarshal(m, b)
}
func (m *SettingsType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsType.Marshal(b, m, deterministic)
}
func (m *SettingsType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsType.Merge(m, src)
}
func (m *SettingsType) XXX_Size() int {
	return xxx_messageInfo_SettingsType.Size(m)
}
func (m *SettingsType) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsType.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsType proto.InternalMessageInfo

func (m *SettingsType) GetCaptureMode() *ECaptureMode {
	if m != nil {
		return m.CaptureMode
	}
	return nil
}

func (m *SettingsType) GetAfterTriggerFilter() *EAfterTriggerFilter {
	if m != nil {
		return m.AfterTriggerFilter
	}
	return nil
}

func (m *SettingsType) GetBeforeTriggerFilter() *EBeforeTriggerFilter {
	if m != nil {
		return m.BeforeTriggerFilter
	}
	return nil
}

func (m *SettingsType) GetContinuousFilter() *EContinuousFilter {
	if m != nil {
		return m.ContinuousFilter
	}
	return nil
}

func (m *SettingsType) GetSliceSize() int32 {
	if m != nil {
		return m.SliceSize
	}
	return 0
}

func (m *SettingsType) GetTriggerPosition() *PFType.KBType {
	if m != nil {
		return m.TriggerPosition
	}
	return nil
}

type ConfigurationType struct {
	Direction            *EDirection     `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Settings             *SettingsType   `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	Patterns             *PatternList    `protobuf:"bytes,3,opt,name=patterns,proto3" json:"patterns,omitempty"`
	Expressions          *ExpressionList `protobuf:"bytes,4,opt,name=expressions,proto3" json:"expressions,omitempty"`
	Rxsharedstat1        *ERXSharedStats `protobuf:"bytes,5,opt,name=rxsharedstat1,proto3" json:"rxsharedstat1,omitempty"`
	Rxsharedstat2        *ERXSharedStats `protobuf:"bytes,6,opt,name=rxsharedstat2,proto3" json:"rxsharedstat2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigurationType) Reset()         { *m = ConfigurationType{} }
func (m *ConfigurationType) String() string { return proto.CompactTextString(m) }
func (*ConfigurationType) ProtoMessage()    {}
func (*ConfigurationType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{8}
}

func (m *ConfigurationType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationType.Unmarshal(m, b)
}
func (m *ConfigurationType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationType.Marshal(b, m, deterministic)
}
func (m *ConfigurationType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationType.Merge(m, src)
}
func (m *ConfigurationType) XXX_Size() int {
	return xxx_messageInfo_ConfigurationType.Size(m)
}
func (m *ConfigurationType) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationType.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationType proto.InternalMessageInfo

func (m *ConfigurationType) GetDirection() *EDirection {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *ConfigurationType) GetSettings() *SettingsType {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ConfigurationType) GetPatterns() *PatternList {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *ConfigurationType) GetExpressions() *ExpressionList {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *ConfigurationType) GetRxsharedstat1() *ERXSharedStats {
	if m != nil {
		return m.Rxsharedstat1
	}
	return nil
}

func (m *ConfigurationType) GetRxsharedstat2() *ERXSharedStats {
	if m != nil {
		return m.Rxsharedstat2
	}
	return nil
}

type EventType struct {
	PortId               *IdType.PortId `protobuf:"bytes,1,opt,name=portId,proto3" json:"portId,omitempty"`
	State                *ECaptureState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CaptureRecords       int32          `protobuf:"varint,3,opt,name=captureRecords,proto3" json:"captureRecords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EventType) Reset()         { *m = EventType{} }
func (m *EventType) String() string { return proto.CompactTextString(m) }
func (*EventType) ProtoMessage()    {}
func (*EventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{9}
}

func (m *EventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventType.Unmarshal(m, b)
}
func (m *EventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventType.Marshal(b, m, deterministic)
}
func (m *EventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventType.Merge(m, src)
}
func (m *EventType) XXX_Size() int {
	return xxx_messageInfo_EventType.Size(m)
}
func (m *EventType) XXX_DiscardUnknown() {
	xxx_messageInfo_EventType.DiscardUnknown(m)
}

var xxx_messageInfo_EventType proto.InternalMessageInfo

func (m *EventType) GetPortId() *IdType.PortId {
	if m != nil {
		return m.PortId
	}
	return nil
}

func (m *EventType) GetState() *ECaptureState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *EventType) GetCaptureRecords() int32 {
	if m != nil {
		return m.CaptureRecords
	}
	return 0
}

type StatusType struct {
	Direction            *EDirection    `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	IsWrapped            bool           `protobuf:"varint,2,opt,name=isWrapped,proto3" json:"isWrapped,omitempty"`
	IsFull               bool           `protobuf:"varint,3,opt,name=isFull,proto3" json:"isFull,omitempty"`
	PktsAvailable        bool           `protobuf:"varint,4,opt,name=pktsAvailable,proto3" json:"pktsAvailable,omitempty"`
	TotalPkts            int32          `protobuf:"varint,5,opt,name=totalPkts,proto3" json:"totalPkts,omitempty"`
	TotalBytes           int64          `protobuf:"varint,6,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
	TriggerIndex         int32          `protobuf:"varint,7,opt,name=triggerIndex,proto3" json:"triggerIndex,omitempty"`
	State                *ECaptureState `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StatusType) Reset()         { *m = StatusType{} }
func (m *StatusType) String() string { return proto.CompactTextString(m) }
func (*StatusType) ProtoMessage()    {}
func (*StatusType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{10}
}

func (m *StatusType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusType.Unmarshal(m, b)
}
func (m *StatusType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusType.Marshal(b, m, deterministic)
}
func (m *StatusType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusType.Merge(m, src)
}
func (m *StatusType) XXX_Size() int {
	return xxx_messageInfo_StatusType.Size(m)
}
func (m *StatusType) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusType.DiscardUnknown(m)
}

var xxx_messageInfo_StatusType proto.InternalMessageInfo

func (m *StatusType) GetDirection() *EDirection {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *StatusType) GetIsWrapped() bool {
	if m != nil {
		return m.IsWrapped
	}
	return false
}

func (m *StatusType) GetIsFull() bool {
	if m != nil {
		return m.IsFull
	}
	return false
}

func (m *StatusType) GetPktsAvailable() bool {
	if m != nil {
		return m.PktsAvailable
	}
	return false
}

func (m *StatusType) GetTotalPkts() int32 {
	if m != nil {
		return m.TotalPkts
	}
	return 0
}

func (m *StatusType) GetTotalBytes() int64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

func (m *StatusType) GetTriggerIndex() int32 {
	if m != nil {
		return m.TriggerIndex
	}
	return 0
}

func (m *StatusType) GetState() *ECaptureState {
	if m != nil {
		return m.State
	}
	return nil
}

type PacketCountType struct {
	Direction            *EDirection `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	TotalPkts            int32       `protobuf:"varint,2,opt,name=totalPkts,proto3" json:"totalPkts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PacketCountType) Reset()         { *m = PacketCountType{} }
func (m *PacketCountType) String() string { return proto.CompactTextString(m) }
func (*PacketCountType) ProtoMessage()    {}
func (*PacketCountType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{11}
}

func (m *PacketCountType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketCountType.Unmarshal(m, b)
}
func (m *PacketCountType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketCountType.Marshal(b, m, deterministic)
}
func (m *PacketCountType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketCountType.Merge(m, src)
}
func (m *PacketCountType) XXX_Size() int {
	return xxx_messageInfo_PacketCountType.Size(m)
}
func (m *PacketCountType) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketCountType.DiscardUnknown(m)
}

var xxx_messageInfo_PacketCountType proto.InternalMessageInfo

func (m *PacketCountType) GetDirection() *EDirection {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *PacketCountType) GetTotalPkts() int32 {
	if m != nil {
		return m.TotalPkts
	}
	return 0
}

type RecordType struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Buffer               uint32   `protobuf:"varint,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordType) Reset()         { *m = RecordType{} }
func (m *RecordType) String() string { return proto.CompactTextString(m) }
func (*RecordType) ProtoMessage()    {}
func (*RecordType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{12}
}

func (m *RecordType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordType.Unmarshal(m, b)
}
func (m *RecordType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordType.Marshal(b, m, deterministic)
}
func (m *RecordType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordType.Merge(m, src)
}
func (m *RecordType) XXX_Size() int {
	return xxx_messageInfo_RecordType.Size(m)
}
func (m *RecordType) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordType.DiscardUnknown(m)
}

var xxx_messageInfo_RecordType proto.InternalMessageInfo

func (m *RecordType) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RecordType) GetBuffer() uint32 {
	if m != nil {
		return m.Buffer
	}
	return 0
}

type RetrieveOptionsType struct {
	StartIndex           int32                `protobuf:"varint,1,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	NumPackets           int32                `protobuf:"varint,2,opt,name=numPackets,proto3" json:"numPackets,omitempty"`
	Direction            *EDirection          `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Format               *EPacketFormat       `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Precision            *ETimestampPrecision `protobuf:"bytes,5,opt,name=precision,proto3" json:"precision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RetrieveOptionsType) Reset()         { *m = RetrieveOptionsType{} }
func (m *RetrieveOptionsType) String() string { return proto.CompactTextString(m) }
func (*RetrieveOptionsType) ProtoMessage()    {}
func (*RetrieveOptionsType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{13}
}

func (m *RetrieveOptionsType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOptionsType.Unmarshal(m, b)
}
func (m *RetrieveOptionsType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOptionsType.Marshal(b, m, deterministic)
}
func (m *RetrieveOptionsType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOptionsType.Merge(m, src)
}
func (m *RetrieveOptionsType) XXX_Size() int {
	return xxx_messageInfo_RetrieveOptionsType.Size(m)
}
func (m *RetrieveOptionsType) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOptionsType.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOptionsType proto.InternalMessageInfo

func (m *RetrieveOptionsType) GetStartIndex() int32 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

func (m *RetrieveOptionsType) GetNumPackets() int32 {
	if m != nil {
		return m.NumPackets
	}
	return 0
}

func (m *RetrieveOptionsType) GetDirection() *EDirection {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *RetrieveOptionsType) GetFormat() *EPacketFormat {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *RetrieveOptionsType) GetPrecision() *ETimestampPrecision {
	if m != nil {
		return m.Precision
	}
	return nil
}

type EDirection struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDirection) Reset()         { *m = EDirection{} }
func (m *EDirection) String() string { return proto.CompactTextString(m) }
func (*EDirection) ProtoMessage()    {}
func (*EDirection) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{14}
}

func (m *EDirection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDirection.Unmarshal(m, b)
}
func (m *EDirection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDirection.Marshal(b, m, deterministic)
}
func (m *EDirection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDirection.Merge(m, src)
}
func (m *EDirection) XXX_Size() int {
	return xxx_messageInfo_EDirection.Size(m)
}
func (m *EDirection) XXX_DiscardUnknown() {
	xxx_messageInfo_EDirection.DiscardUnknown(m)
}

var xxx_messageInfo_EDirection proto.InternalMessageInfo

type EPacketFormat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EPacketFormat) Reset()         { *m = EPacketFormat{} }
func (m *EPacketFormat) String() string { return proto.CompactTextString(m) }
func (*EPacketFormat) ProtoMessage()    {}
func (*EPacketFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{15}
}

func (m *EPacketFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPacketFormat.Unmarshal(m, b)
}
func (m *EPacketFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPacketFormat.Marshal(b, m, deterministic)
}
func (m *EPacketFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPacketFormat.Merge(m, src)
}
func (m *EPacketFormat) XXX_Size() int {
	return xxx_messageInfo_EPacketFormat.Size(m)
}
func (m *EPacketFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_EPacketFormat.DiscardUnknown(m)
}

var xxx_messageInfo_EPacketFormat proto.InternalMessageInfo

type ETimestampPrecision struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETimestampPrecision) Reset()         { *m = ETimestampPrecision{} }
func (m *ETimestampPrecision) String() string { return proto.CompactTextString(m) }
func (*ETimestampPrecision) ProtoMessage()    {}
func (*ETimestampPrecision) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{16}
}

func (m *ETimestampPrecision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETimestampPrecision.Unmarshal(m, b)
}
func (m *ETimestampPrecision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETimestampPrecision.Marshal(b, m, deterministic)
}
func (m *ETimestampPrecision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETimestampPrecision.Merge(m, src)
}
func (m *ETimestampPrecision) XXX_Size() int {
	return xxx_messageInfo_ETimestampPrecision.Size(m)
}
func (m *ETimestampPrecision) XXX_DiscardUnknown() {
	xxx_messageInfo_ETimestampPrecision.DiscardUnknown(m)
}

var xxx_messageInfo_ETimestampPrecision proto.InternalMessageInfo

type EPatternKind struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EPatternKind) Reset()         { *m = EPatternKind{} }
func (m *EPatternKind) String() string { return proto.CompactTextString(m) }
func (*EPatternKind) ProtoMessage()    {}
func (*EPatternKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{17}
}

func (m *EPatternKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPatternKind.Unmarshal(m, b)
}
func (m *EPatternKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPatternKind.Marshal(b, m, deterministic)
}
func (m *EPatternKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPatternKind.Merge(m, src)
}
func (m *EPatternKind) XXX_Size() int {
	return xxx_messageInfo_EPatternKind.Size(m)
}
func (m *EPatternKind) XXX_DiscardUnknown() {
	xxx_messageInfo_EPatternKind.DiscardUnknown(m)
}

var xxx_messageInfo_EPatternKind proto.InternalMessageInfo

type EExpressionKind struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EExpressionKind) Reset()         { *m = EExpressionKind{} }
func (m *EExpressionKind) String() string { return proto.CompactTextString(m) }
func (*EExpressionKind) ProtoMessage()    {}
func (*EExpressionKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{18}
}

func (m *EExpressionKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EExpressionKind.Unmarshal(m, b)
}
func (m *EExpressionKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EExpressionKind.Marshal(b, m, deterministic)
}
func (m *EExpressionKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EExpressionKind.Merge(m, src)
}
func (m *EExpressionKind) XXX_Size() int {
	return xxx_messageInfo_EExpressionKind.Size(m)
}
func (m *EExpressionKind) XXX_DiscardUnknown() {
	xxx_messageInfo_EExpressionKind.DiscardUnknown(m)
}

var xxx_messageInfo_EExpressionKind proto.InternalMessageInfo

type EAfterTriggerFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EAfterTriggerFilter) Reset()         { *m = EAfterTriggerFilter{} }
func (m *EAfterTriggerFilter) String() string { return proto.CompactTextString(m) }
func (*EAfterTriggerFilter) ProtoMessage()    {}
func (*EAfterTriggerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{19}
}

func (m *EAfterTriggerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EAfterTriggerFilter.Unmarshal(m, b)
}
func (m *EAfterTriggerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EAfterTriggerFilter.Marshal(b, m, deterministic)
}
func (m *EAfterTriggerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EAfterTriggerFilter.Merge(m, src)
}
func (m *EAfterTriggerFilter) XXX_Size() int {
	return xxx_messageInfo_EAfterTriggerFilter.Size(m)
}
func (m *EAfterTriggerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EAfterTriggerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EAfterTriggerFilter proto.InternalMessageInfo

type EBeforeTriggerFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EBeforeTriggerFilter) Reset()         { *m = EBeforeTriggerFilter{} }
func (m *EBeforeTriggerFilter) String() string { return proto.CompactTextString(m) }
func (*EBeforeTriggerFilter) ProtoMessage()    {}
func (*EBeforeTriggerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{20}
}

func (m *EBeforeTriggerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EBeforeTriggerFilter.Unmarshal(m, b)
}
func (m *EBeforeTriggerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EBeforeTriggerFilter.Marshal(b, m, deterministic)
}
func (m *EBeforeTriggerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EBeforeTriggerFilter.Merge(m, src)
}
func (m *EBeforeTriggerFilter) XXX_Size() int {
	return xxx_messageInfo_EBeforeTriggerFilter.Size(m)
}
func (m *EBeforeTriggerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EBeforeTriggerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EBeforeTriggerFilter proto.InternalMessageInfo

type EContinuousFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EContinuousFilter) Reset()         { *m = EContinuousFilter{} }
func (m *EContinuousFilter) String() string { return proto.CompactTextString(m) }
func (*EContinuousFilter) ProtoMessage()    {}
func (*EContinuousFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{21}
}

func (m *EContinuousFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EContinuousFilter.Unmarshal(m, b)
}
func (m *EContinuousFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EContinuousFilter.Marshal(b, m, deterministic)
}
func (m *EContinuousFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EContinuousFilter.Merge(m, src)
}
func (m *EContinuousFilter) XXX_Size() int {
	return xxx_messageInfo_EContinuousFilter.Size(m)
}
func (m *EContinuousFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EContinuousFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EContinuousFilter proto.InternalMessageInfo

type ECaptureMode struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECaptureMode) Reset()         { *m = ECaptureMode{} }
func (m *ECaptureMode) String() string { return proto.CompactTextString(m) }
func (*ECaptureMode) ProtoMessage()    {}
func (*ECaptureMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{22}
}

func (m *ECaptureMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECaptureMode.Unmarshal(m, b)
}
func (m *ECaptureMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECaptureMode.Marshal(b, m, deterministic)
}
func (m *ECaptureMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECaptureMode.Merge(m, src)
}
func (m *ECaptureMode) XXX_Size() int {
	return xxx_messageInfo_ECaptureMode.Size(m)
}
func (m *ECaptureMode) XXX_DiscardUnknown() {
	xxx_messageInfo_ECaptureMode.DiscardUnknown(m)
}

var xxx_messageInfo_ECaptureMode proto.InternalMessageInfo

type ECaptureState struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECaptureState) Reset()         { *m = ECaptureState{} }
func (m *ECaptureState) String() string { return proto.CompactTextString(m) }
func (*ECaptureState) ProtoMessage()    {}
func (*ECaptureState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{23}
}

func (m *ECaptureState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECaptureState.Unmarshal(m, b)
}
func (m *ECaptureState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECaptureState.Marshal(b, m, deterministic)
}
func (m *ECaptureState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECaptureState.Merge(m, src)
}
func (m *ECaptureState) XXX_Size() int {
	return xxx_messageInfo_ECaptureState.Size(m)
}
func (m *ECaptureState) XXX_DiscardUnknown() {
	xxx_messageInfo_ECaptureState.DiscardUnknown(m)
}

var xxx_messageInfo_ECaptureState proto.InternalMessageInfo

type EAnchor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EAnchor) Reset()         { *m = EAnchor{} }
func (m *EAnchor) String() string { return proto.CompactTextString(m) }
func (*EAnchor) ProtoMessage()    {}
func (*EAnchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{24}
}

func (m *EAnchor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EAnchor.Unmarshal(m, b)
}
func (m *EAnchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EAnchor.Marshal(b, m, deterministic)
}
func (m *EAnchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EAnchor.Merge(m, src)
}
func (m *EAnchor) XXX_Size() int {
	return xxx_messageInfo_EAnchor.Size(m)
}
func (m *EAnchor) XXX_DiscardUnknown() {
	xxx_messageInfo_EAnchor.DiscardUnknown(m)
}

var xxx_messageInfo_EAnchor proto.InternalMessageInfo

type ELogic struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ELogic) Reset()         { *m = ELogic{} }
func (m *ELogic) String() string { return proto.CompactTextString(m) }
func (*ELogic) ProtoMessage()    {}
func (*ELogic) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{25}
}

func (m *ELogic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ELogic.Unmarshal(m, b)
}
func (m *ELogic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ELogic.Marshal(b, m, deterministic)
}
func (m *ELogic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ELogic.Merge(m, src)
}
func (m *ELogic) XXX_Size() int {
	return xxx_messageInfo_ELogic.Size(m)
}
func (m *ELogic) XXX_DiscardUnknown() {
	xxx_messageInfo_ELogic.DiscardUnknown(m)
}

var xxx_messageInfo_ELogic proto.InternalMessageInfo

type EErrorMatch struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EErrorMatch) Reset()         { *m = EErrorMatch{} }
func (m *EErrorMatch) String() string { return proto.CompactTextString(m) }
func (*EErrorMatch) ProtoMessage()    {}
func (*EErrorMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{26}
}

func (m *EErrorMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EErrorMatch.Unmarshal(m, b)
}
func (m *EErrorMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EErrorMatch.Marshal(b, m, deterministic)
}
func (m *EErrorMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EErrorMatch.Merge(m, src)
}
func (m *EErrorMatch) XXX_Size() int {
	return xxx_messageInfo_EErrorMatch.Size(m)
}
func (m *EErrorMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_EErrorMatch.DiscardUnknown(m)
}

var xxx_messageInfo_EErrorMatch proto.InternalMessageInfo

type ECircuitList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECircuitList) Reset()         { *m = ECircuitList{} }
func (m *ECircuitList) String() string { return proto.CompactTextString(m) }
func (*ECircuitList) ProtoMessage()    {}
func (*ECircuitList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{27}
}

func (m *ECircuitList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECircuitList.Unmarshal(m, b)
}
func (m *ECircuitList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECircuitList.Marshal(b, m, deterministic)
}
func (m *ECircuitList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECircuitList.Merge(m, src)
}
func (m *ECircuitList) XXX_Size() int {
	return xxx_messageInfo_ECircuitList.Size(m)
}
func (m *ECircuitList) XXX_DiscardUnknown() {
	xxx_messageInfo_ECircuitList.DiscardUnknown(m)
}

var xxx_messageInfo_ECircuitList proto.InternalMessageInfo

type EExpressionElementKind struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EExpressionElementKind) Reset()         { *m = EExpressionElementKind{} }
func (m *EExpressionElementKind) String() string { return proto.CompactTextString(m) }
func (*EExpressionElementKind) ProtoMessage()    {}
func (*EExpressionElementKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{28}
}

func (m *EExpressionElementKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EExpressionElementKind.Unmarshal(m, b)
}
func (m *EExpressionElementKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EExpressionElementKind.Marshal(b, m, deterministic)
}
func (m *EExpressionElementKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EExpressionElementKind.Merge(m, src)
}
func (m *EExpressionElementKind) XXX_Size() int {
	return xxx_messageInfo_EExpressionElementKind.Size(m)
}
func (m *EExpressionElementKind) XXX_DiscardUnknown() {
	xxx_messageInfo_EExpressionElementKind.DiscardUnknown(m)
}

var xxx_messageInfo_EExpressionElementKind proto.InternalMessageInfo

type EFilterExpressionParserType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EFilterExpressionParserType) Reset()         { *m = EFilterExpressionParserType{} }
func (m *EFilterExpressionParserType) String() string { return proto.CompactTextString(m) }
func (*EFilterExpressionParserType) ProtoMessage()    {}
func (*EFilterExpressionParserType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{29}
}

func (m *EFilterExpressionParserType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EFilterExpressionParserType.Unmarshal(m, b)
}
func (m *EFilterExpressionParserType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EFilterExpressionParserType.Marshal(b, m, deterministic)
}
func (m *EFilterExpressionParserType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EFilterExpressionParserType.Merge(m, src)
}
func (m *EFilterExpressionParserType) XXX_Size() int {
	return xxx_messageInfo_EFilterExpressionParserType.Size(m)
}
func (m *EFilterExpressionParserType) XXX_DiscardUnknown() {
	xxx_messageInfo_EFilterExpressionParserType.DiscardUnknown(m)
}

var xxx_messageInfo_EFilterExpressionParserType proto.InternalMessageInfo

type ERXSharedStats struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ERXSharedStats) Reset()         { *m = ERXSharedStats{} }
func (m *ERXSharedStats) String() string { return proto.CompactTextString(m) }
func (*ERXSharedStats) ProtoMessage()    {}
func (*ERXSharedStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{30}
}

func (m *ERXSharedStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERXSharedStats.Unmarshal(m, b)
}
func (m *ERXSharedStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERXSharedStats.Marshal(b, m, deterministic)
}
func (m *ERXSharedStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERXSharedStats.Merge(m, src)
}
func (m *ERXSharedStats) XXX_Size() int {
	return xxx_messageInfo_ERXSharedStats.Size(m)
}
func (m *ERXSharedStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ERXSharedStats.DiscardUnknown(m)
}

var xxx_messageInfo_ERXSharedStats proto.InternalMessageInfo

type PatternList struct {
	PatternList          []*PatternType `protobuf:"bytes,1,rep,name=PatternList,proto3" json:"PatternList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PatternList) Reset()         { *m = PatternList{} }
func (m *PatternList) String() string { return proto.CompactTextString(m) }
func (*PatternList) ProtoMessage()    {}
func (*PatternList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{31}
}

func (m *PatternList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatternList.Unmarshal(m, b)
}
func (m *PatternList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatternList.Marshal(b, m, deterministic)
}
func (m *PatternList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatternList.Merge(m, src)
}
func (m *PatternList) XXX_Size() int {
	return xxx_messageInfo_PatternList.Size(m)
}
func (m *PatternList) XXX_DiscardUnknown() {
	xxx_messageInfo_PatternList.DiscardUnknown(m)
}

var xxx_messageInfo_PatternList proto.InternalMessageInfo

func (m *PatternList) GetPatternList() []*PatternType {
	if m != nil {
		return m.PatternList
	}
	return nil
}

type ExpressionContent struct {
	ExpressionContent    []*ExpressionElementType `protobuf:"bytes,1,rep,name=ExpressionContent,proto3" json:"ExpressionContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ExpressionContent) Reset()         { *m = ExpressionContent{} }
func (m *ExpressionContent) String() string { return proto.CompactTextString(m) }
func (*ExpressionContent) ProtoMessage()    {}
func (*ExpressionContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{32}
}

func (m *ExpressionContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionContent.Unmarshal(m, b)
}
func (m *ExpressionContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionContent.Marshal(b, m, deterministic)
}
func (m *ExpressionContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionContent.Merge(m, src)
}
func (m *ExpressionContent) XXX_Size() int {
	return xxx_messageInfo_ExpressionContent.Size(m)
}
func (m *ExpressionContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionContent.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionContent proto.InternalMessageInfo

func (m *ExpressionContent) GetExpressionContent() []*ExpressionElementType {
	if m != nil {
		return m.ExpressionContent
	}
	return nil
}

type ExpressionList struct {
	ExpressionList       []*ExpressionType `protobuf:"bytes,1,rep,name=ExpressionList,proto3" json:"ExpressionList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExpressionList) Reset()         { *m = ExpressionList{} }
func (m *ExpressionList) String() string { return proto.CompactTextString(m) }
func (*ExpressionList) ProtoMessage()    {}
func (*ExpressionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{33}
}

func (m *ExpressionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionList.Unmarshal(m, b)
}
func (m *ExpressionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionList.Marshal(b, m, deterministic)
}
func (m *ExpressionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionList.Merge(m, src)
}
func (m *ExpressionList) XXX_Size() int {
	return xxx_messageInfo_ExpressionList.Size(m)
}
func (m *ExpressionList) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionList.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionList proto.InternalMessageInfo

func (m *ExpressionList) GetExpressionList() []*ExpressionType {
	if m != nil {
		return m.ExpressionList
	}
	return nil
}

type ConfigurationList struct {
	ConfigurationList    []*ConfigurationType `protobuf:"bytes,1,rep,name=ConfigurationList,proto3" json:"ConfigurationList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConfigurationList) Reset()         { *m = ConfigurationList{} }
func (m *ConfigurationList) String() string { return proto.CompactTextString(m) }
func (*ConfigurationList) ProtoMessage()    {}
func (*ConfigurationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{34}
}

func (m *ConfigurationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationList.Unmarshal(m, b)
}
func (m *ConfigurationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationList.Marshal(b, m, deterministic)
}
func (m *ConfigurationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationList.Merge(m, src)
}
func (m *ConfigurationList) XXX_Size() int {
	return xxx_messageInfo_ConfigurationList.Size(m)
}
func (m *ConfigurationList) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationList.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationList proto.InternalMessageInfo

func (m *ConfigurationList) GetConfigurationList() []*ConfigurationType {
	if m != nil {
		return m.ConfigurationList
	}
	return nil
}

type StatusList struct {
	StatusList           []*StatusType `protobuf:"bytes,1,rep,name=StatusList,proto3" json:"StatusList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatusList) Reset()         { *m = StatusList{} }
func (m *StatusList) String() string { return proto.CompactTextString(m) }
func (*StatusList) ProtoMessage()    {}
func (*StatusList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{35}
}

func (m *StatusList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusList.Unmarshal(m, b)
}
func (m *StatusList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusList.Marshal(b, m, deterministic)
}
func (m *StatusList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusList.Merge(m, src)
}
func (m *StatusList) XXX_Size() int {
	return xxx_messageInfo_StatusList.Size(m)
}
func (m *StatusList) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusList.DiscardUnknown(m)
}

var xxx_messageInfo_StatusList proto.InternalMessageInfo

func (m *StatusList) GetStatusList() []*StatusType {
	if m != nil {
		return m.StatusList
	}
	return nil
}

type PacketCountList struct {
	PacketCountList      []*PacketCountType `protobuf:"bytes,1,rep,name=PacketCountList,proto3" json:"PacketCountList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PacketCountList) Reset()         { *m = PacketCountList{} }
func (m *PacketCountList) String() string { return proto.CompactTextString(m) }
func (*PacketCountList) ProtoMessage()    {}
func (*PacketCountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a592909caf2b3a, []int{36}
}

func (m *PacketCountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketCountList.Unmarshal(m, b)
}
func (m *PacketCountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketCountList.Marshal(b, m, deterministic)
}
func (m *PacketCountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketCountList.Merge(m, src)
}
func (m *PacketCountList) XXX_Size() int {
	return xxx_messageInfo_PacketCountList.Size(m)
}
func (m *PacketCountList) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketCountList.DiscardUnknown(m)
}

var xxx_messageInfo_PacketCountList proto.InternalMessageInfo

func (m *PacketCountList) GetPacketCountList() []*PacketCountType {
	if m != nil {
		return m.PacketCountList
	}
	return nil
}

func init() {
	proto.RegisterEnum("Capture.EDirection_Enum", EDirection_Enum_name, EDirection_Enum_value)
	proto.RegisterEnum("Capture.EPacketFormat_Enum", EPacketFormat_Enum_name, EPacketFormat_Enum_value)
	proto.RegisterEnum("Capture.ETimestampPrecision_Enum", ETimestampPrecision_Enum_name, ETimestampPrecision_Enum_value)
	proto.RegisterEnum("Capture.EPatternKind_Enum", EPatternKind_Enum_name, EPatternKind_Enum_value)
	proto.RegisterEnum("Capture.EExpressionKind_Enum", EExpressionKind_Enum_name, EExpressionKind_Enum_value)
	proto.RegisterEnum("Capture.EAfterTriggerFilter_Enum", EAfterTriggerFilter_Enum_name, EAfterTriggerFilter_Enum_value)
	proto.RegisterEnum("Capture.EBeforeTriggerFilter_Enum", EBeforeTriggerFilter_Enum_name, EBeforeTriggerFilter_Enum_value)
	proto.RegisterEnum("Capture.EContinuousFilter_Enum", EContinuousFilter_Enum_name, EContinuousFilter_Enum_value)
	proto.RegisterEnum("Capture.ECaptureMode_Enum", ECaptureMode_Enum_name, ECaptureMode_Enum_value)
	proto.RegisterEnum("Capture.ECaptureState_Enum", ECaptureState_Enum_name, ECaptureState_Enum_value)
	proto.RegisterEnum("Capture.EAnchor_Enum", EAnchor_Enum_name, EAnchor_Enum_value)
	proto.RegisterEnum("Capture.ELogic_Enum", ELogic_Enum_name, ELogic_Enum_value)
	proto.RegisterEnum("Capture.EErrorMatch_Enum", EErrorMatch_Enum_name, EErrorMatch_Enum_value)
	proto.RegisterEnum("Capture.ECircuitList_Enum", ECircuitList_Enum_name, ECircuitList_Enum_value)
	proto.RegisterEnum("Capture.EExpressionElementKind_Enum", EExpressionElementKind_Enum_name, EExpressionElementKind_Enum_value)
	proto.RegisterEnum("Capture.EFilterExpressionParserType_Enum", EFilterExpressionParserType_Enum_name, EFilterExpressionParserType_Enum_value)
	proto.RegisterEnum("Capture.ERXSharedStats_Enum", ERXSharedStats_Enum_name, ERXSharedStats_Enum_value)
	proto.RegisterType((*QoSPatternType)(nil), "Capture.QoSPatternType")
	proto.RegisterType((*DataPatternType)(nil), "Capture.DataPatternType")
	proto.RegisterType((*MacPatternType)(nil), "Capture.MacPatternType")
	proto.RegisterType((*PatternType)(nil), "Capture.PatternType")
	proto.RegisterType((*FrameSizeRangeType)(nil), "Capture.FrameSizeRangeType")
	proto.RegisterType((*ExpressionElementType)(nil), "Capture.ExpressionElementType")
	proto.RegisterType((*ExpressionType)(nil), "Capture.ExpressionType")
	proto.RegisterType((*SettingsType)(nil), "Capture.SettingsType")
	proto.RegisterType((*ConfigurationType)(nil), "Capture.ConfigurationType")
	proto.RegisterType((*EventType)(nil), "Capture.EventType")
	proto.RegisterType((*StatusType)(nil), "Capture.StatusType")
	proto.RegisterType((*PacketCountType)(nil), "Capture.PacketCountType")
	proto.RegisterType((*RecordType)(nil), "Capture.RecordType")
	proto.RegisterType((*RetrieveOptionsType)(nil), "Capture.RetrieveOptionsType")
	proto.RegisterType((*EDirection)(nil), "Capture.eDirection")
	proto.RegisterType((*EPacketFormat)(nil), "Capture.ePacketFormat")
	proto.RegisterType((*ETimestampPrecision)(nil), "Capture.eTimestampPrecision")
	proto.RegisterType((*EPatternKind)(nil), "Capture.ePatternKind")
	proto.RegisterType((*EExpressionKind)(nil), "Capture.eExpressionKind")
	proto.RegisterType((*EAfterTriggerFilter)(nil), "Capture.eAfterTriggerFilter")
	proto.RegisterType((*EBeforeTriggerFilter)(nil), "Capture.eBeforeTriggerFilter")
	proto.RegisterType((*EContinuousFilter)(nil), "Capture.eContinuousFilter")
	proto.RegisterType((*ECaptureMode)(nil), "Capture.eCaptureMode")
	proto.RegisterType((*ECaptureState)(nil), "Capture.eCaptureState")
	proto.RegisterType((*EAnchor)(nil), "Capture.eAnchor")
	proto.RegisterType((*ELogic)(nil), "Capture.eLogic")
	proto.RegisterType((*EErrorMatch)(nil), "Capture.eErrorMatch")
	proto.RegisterType((*ECircuitList)(nil), "Capture.eCircuitList")
	proto.RegisterType((*EExpressionElementKind)(nil), "Capture.eExpressionElementKind")
	proto.RegisterType((*EFilterExpressionParserType)(nil), "Capture.eFilterExpressionParserType")
	proto.RegisterType((*ERXSharedStats)(nil), "Capture.eRXSharedStats")
	proto.RegisterType((*PatternList)(nil), "Capture.PatternList")
	proto.RegisterType((*ExpressionContent)(nil), "Capture.ExpressionContent")
	proto.RegisterType((*ExpressionList)(nil), "Capture.ExpressionList")
	proto.RegisterType((*ConfigurationList)(nil), "Capture.ConfigurationList")
	proto.RegisterType((*StatusList)(nil), "Capture.StatusList")
	proto.RegisterType((*PacketCountList)(nil), "Capture.PacketCountList")
}

func init() { proto.RegisterFile("Capture/Capture.proto", fileDescriptor_a2a592909caf2b3a) }

var fileDescriptor_a2a592909caf2b3a = []byte{
	// 2004 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x58, 0x5f, 0x73, 0x23, 0x47,
	0x11, 0x47, 0xff, 0x6c, 0xb9, 0x65, 0xcb, 0xf2, 0xca, 0xe7, 0x53, 0xf9, 0x8e, 0x90, 0x1a, 0x52,
	0x54, 0x28, 0x82, 0x93, 0x5c, 0xf8, 0x97, 0x54, 0x85, 0x8b, 0x2d, 0xdb, 0xc1, 0xe4, 0xee, 0xac,
	0x8c, 0x6c, 0xb8, 0xa2, 0xa0, 0xa8, 0xf5, 0xee, 0xc8, 0xb7, 0xa5, 0xd5, 0xae, 0xb2, 0xbb, 0x32,
	0x3e, 0x1e, 0x78, 0x83, 0x2a, 0xbe, 0x0a, 0xbc, 0xf2, 0xc2, 0x47, 0xa0, 0x8a, 0x0f, 0xc0, 0x07,
	0xe0, 0x81, 0x0f, 0x00, 0xef, 0xf4, 0xcc, 0xf4, 0xee, 0xcc, 0x6a, 0xe5, 0xbb, 0xab, 0x3c, 0x49,
	0xd3, 0x7f, 0x7e, 0xdd, 0xd3, 0xdd, 0xd3, 0xd3, 0xb3, 0x70, 0x6f, 0xe8, 0xce, 0xb3, 0x45, 0x22,
	0xde, 0xa7, 0xdf, 0x83, 0x79, 0x12, 0x67, 0xb1, 0xb3, 0x4e, 0xcb, 0xfd, 0xfe, 0xe8, 0xf4, 0xe2,
	0xe5, 0x5c, 0xbc, 0xaf, 0x7f, 0x34, 0x77, 0xbf, 0x7f, 0xe6, 0x2b, 0xa2, 0xfe, 0xd1, 0x44, 0xf6,
	0x97, 0x1a, 0x74, 0xbf, 0x8c, 0xc7, 0x23, 0x37, 0xcb, 0x44, 0x12, 0x49, 0x86, 0xf3, 0x0e, 0x6c,
	0x7d, 0x15, 0xa7, 0x47, 0x2f, 0x33, 0x71, 0x3e, 0x99, 0xa4, 0x22, 0x1b, 0xd4, 0xde, 0xae, 0xbd,
	0xdb, 0xe2, 0x65, 0xa2, 0xf3, 0x2e, 0xac, 0xb9, 0x91, 0xf7, 0x22, 0x4e, 0x06, 0x75, 0x64, 0x77,
	0x1e, 0xf5, 0x0e, 0x72, 0x5f, 0xc4, 0xa1, 0xa2, 0x73, 0xe2, 0x3b, 0x7b, 0xb0, 0x16, 0x6b, 0xa0,
	0x86, 0x02, 0xa2, 0x95, 0x33, 0x80, 0xf5, 0xb9, 0x36, 0x3b, 0x68, 0x22, 0x63, 0x8b, 0xe7, 0x4b,
	0xa9, 0x91, 0x8a, 0x50, 0x78, 0xd9, 0xa0, 0xa5, 0x18, 0xb4, 0x62, 0x7f, 0xac, 0xc1, 0xf6, 0xb1,
	0x9b, 0xb9, 0xb6, 0xb7, 0xc6, 0x8f, 0xda, 0x1b, 0xfb, 0x51, 0xbf, 0xcb, 0x8f, 0xc6, 0x5d, 0x7e,
	0x34, 0x4b, 0x7e, 0x24, 0xd0, 0x7d, 0xea, 0x7a, 0xb6, 0x17, 0x1f, 0xc0, 0xba, 0xeb, 0xfb, 0x89,
	0x48, 0x53, 0x72, 0x63, 0xef, 0x80, 0x62, 0x8f, 0x82, 0x87, 0x9a, 0x23, 0x97, 0x3c, 0x17, 0x73,
	0x0e, 0x0a, 0xec, 0xfa, 0x2b, 0x15, 0x72, 0x9b, 0xff, 0xab, 0x43, 0xc7, 0xb6, 0xf8, 0x23, 0xd8,
	0x20, 0x37, 0xcf, 0x7c, 0xb2, 0x39, 0x38, 0xa0, 0xd4, 0x52, 0x04, 0x46, 0x39, 0x9f, 0x1b, 0x51,
	0xe7, 0xc7, 0xd0, 0xa1, 0xc5, 0x17, 0x41, 0xe4, 0x93, 0xf1, 0x7b, 0x26, 0x68, 0x23, 0xc3, 0xe4,
	0xb6, 0xa4, 0xf3, 0x18, 0xba, 0x69, 0xa2, 0x5c, 0x1b, 0x59, 0xd1, 0xea, 0x3c, 0xba, 0x5f, 0xe8,
	0x96, 0x63, 0xc2, 0x97, 0xc4, 0x25, 0x80, 0x9f, 0x66, 0x36, 0x40, 0xf3, 0x35, 0x00, 0x65, 0x71,
	0xe7, 0x13, 0xe8, 0xf8, 0x26, 0xfb, 0xaa, 0x36, 0xe4, 0xa6, 0x73, 0xed, 0xa5, 0xca, 0xe0, 0xb6,
	0x30, 0x6e, 0x1b, 0xb0, 0x7e, 0x73, 0xd5, 0xb5, 0x25, 0xc3, 0xe5, 0x13, 0xc0, 0x2d, 0x51, 0x96,
	0x81, 0x73, 0x9a, 0xb8, 0x33, 0x31, 0x0e, 0x7e, 0x2f, 0xb8, 0x1b, 0x5d, 0x0b, 0x15, 0xfd, 0x87,
	0xb0, 0x11, 0xa4, 0x27, 0x91, 0x7b, 0x15, 0x0a, 0x1d, 0xfd, 0x36, 0x37, 0x04, 0xcd, 0x3d, 0x8b,
	0x94, 0xb8, 0x8a, 0xb0, 0xe2, 0x12, 0xc1, 0x71, 0xa0, 0x39, 0x49, 0xe2, 0x19, 0x9d, 0x06, 0xf5,
	0xdf, 0xe9, 0x42, 0x3d, 0x8b, 0x55, 0x3c, 0x5a, 0x1c, 0xff, 0xb1, 0x7f, 0xd4, 0xe0, 0xde, 0xc9,
	0xed, 0x5c, 0x56, 0x41, 0x10, 0x47, 0x27, 0xa1, 0x98, 0x89, 0x28, 0x53, 0x96, 0x0f, 0xa1, 0x23,
	0xf4, 0x52, 0xe5, 0x4f, 0x67, 0xfe, 0x5b, 0x26, 0x7f, 0x15, 0x2d, 0x9d, 0x49, 0x4b, 0xc7, 0xf9,
	0x21, 0x6c, 0xc5, 0x73, 0x91, 0xb8, 0x59, 0x9c, 0x3c, 0x89, 0xaf, 0x03, 0x8f, 0x8a, 0x60, 0xdb,
	0x80, 0x28, 0x32, 0x2f, 0x4b, 0x95, 0x2b, 0xae, 0xf1, 0xc6, 0x15, 0xc7, 0xfe, 0xd6, 0x84, 0xae,
	0xf1, 0x4a, 0x6d, 0xe2, 0x33, 0xe8, 0x8a, 0x82, 0x62, 0xed, 0x63, 0xb0, 0x6a, 0x1f, 0x6a, 0x03,
	0x4b, 0xf2, 0xce, 0x0f, 0x00, 0x44, 0x92, 0xc4, 0xc9, 0x53, 0x37, 0xf3, 0x5e, 0xd0, 0x06, 0x76,
	0x2d, 0xed, 0x82, 0xc7, 0x2d, 0x39, 0x67, 0x08, 0xdd, 0x49, 0x29, 0x99, 0xb4, 0x8f, 0x07, 0x85,
	0x66, 0x35, 0xd7, 0x7c, 0x49, 0x05, 0x33, 0xd0, 0x4b, 0xe3, 0x48, 0x64, 0xc3, 0x20, 0xf1, 0x16,
	0x41, 0xf6, 0x24, 0x48, 0x33, 0xaa, 0x64, 0xeb, 0x18, 0x59, 0x4c, 0x5e, 0x11, 0xc7, 0xfd, 0x6f,
	0x4d, 0x82, 0x10, 0xe3, 0x33, 0x8c, 0xa3, 0x0c, 0xd3, 0x42, 0xb5, 0xbc, 0x5f, 0xe8, 0x9b, 0xdd,
	0x93, 0x04, 0x2f, 0x2b, 0x60, 0xc3, 0xe9, 0x63, 0xbd, 0x99, 0x5c, 0x53, 0x29, 0xae, 0xa9, 0x62,
	0x5b, 0xc5, 0x72, 0x2e, 0xe0, 0xbe, 0x86, 0xa8, 0x60, 0x0f, 0xd6, 0x5f, 0x6b, 0xfd, 0x2e, 0x55,
	0xe7, 0x39, 0xec, 0x9a, 0xcc, 0x8c, 0xdc, 0x24, 0x15, 0x89, 0x0c, 0xda, 0xa0, 0xad, 0x20, 0xdf,
	0x31, 0x01, 0x39, 0x5d, 0x02, 0x30, 0xb2, 0x7c, 0x25, 0x02, 0xfb, 0x53, 0x03, 0x36, 0xc7, 0x22,
	0xcb, 0x82, 0xe8, 0x5a, 0x75, 0x42, 0xd9, 0xb9, 0x3c, 0x8d, 0xf6, 0x34, 0xf6, 0x05, 0x55, 0x8c,
	0x1d, 0x72, 0xc3, 0xe4, 0xb6, 0xa4, 0xf3, 0x04, 0x1c, 0x77, 0x82, 0xc6, 0x2f, 0x92, 0xe0, 0xfa,
	0x5a, 0x24, 0xda, 0x13, 0xaa, 0x99, 0x87, 0xd6, 0x75, 0x51, 0x91, 0xe1, 0x2b, 0xf4, 0x9c, 0x73,
	0xe8, 0x5f, 0x89, 0x49, 0x9c, 0x88, 0x32, 0x9c, 0x2e, 0xa4, 0x6f, 0x1a, 0xb8, 0xa3, 0xaa, 0x10,
	0x5f, 0xa5, 0xe9, 0x9c, 0x42, 0xcf, 0xc3, 0x68, 0x06, 0xd1, 0x22, 0x5e, 0xa4, 0x84, 0xd6, 0x5c,
	0xca, 0x88, 0x18, 0x2e, 0x49, 0xf0, 0x8a, 0x8e, 0xec, 0x3a, 0x69, 0x18, 0x78, 0xaa, 0x52, 0x55,
	0x41, 0xb5, 0xb8, 0x21, 0x38, 0x3f, 0x81, 0xed, 0x4c, 0x9b, 0x1d, 0xc5, 0x69, 0x90, 0x61, 0xac,
	0xa9, 0x0b, 0x76, 0xf3, 0x8b, 0xe7, 0x8b, 0x23, 0x95, 0x8d, 0x65, 0x31, 0xf6, 0xef, 0x3a, 0xec,
	0xa0, 0xf9, 0x49, 0x70, 0xbd, 0xc0, 0x6e, 0x90, 0x1f, 0xe1, 0x0f, 0x61, 0xc3, 0x0f, 0x12, 0xbc,
	0x99, 0x24, 0x92, 0xce, 0x45, 0xdf, 0xb8, 0x7b, 0x9c, 0xb3, 0xb8, 0x91, 0x42, 0x95, 0x76, 0x4a,
	0x09, 0xad, 0xdc, 0x3b, 0x76, 0xa6, 0x79, 0x21, 0x86, 0x65, 0xde, 0xa6, 0x46, 0x92, 0x52, 0x84,
	0xcd, 0x21, 0xa7, 0x66, 0xa3, 0x8e, 0x58, 0x21, 0xe5, 0x7c, 0x8c, 0xfd, 0xb1, 0x28, 0xa7, 0xb4,
	0x72, 0xc5, 0x98, 0x02, 0x54, 0x7a, 0xb6, 0xac, 0xf3, 0x29, 0x6c, 0x25, 0xb7, 0xe9, 0x0b, 0x37,
	0x11, 0x78, 0xf1, 0xb8, 0xd9, 0x87, 0x74, 0x2a, 0x8d, 0xb2, 0xe0, 0xcf, 0xc7, 0x8a, 0x3d, 0x46,
	0x76, 0xca, 0xcb, 0xd2, 0xcb, 0xea, 0x8f, 0x2a, 0xb7, 0xcc, 0xab, 0xd4, 0x1f, 0xb1, 0x3f, 0xd7,
	0x60, 0xe3, 0xe4, 0x26, 0x6f, 0xf3, 0xdf, 0x81, 0xb5, 0x79, 0x9c, 0x64, 0xc5, 0xdd, 0xde, 0xcd,
	0x3b, 0xed, 0x48, 0x51, 0x39, 0x71, 0x9d, 0xf7, 0xa0, 0x25, 0xd5, 0x45, 0x31, 0x45, 0x2c, 0x1f,
	0x07, 0x69, 0x4b, 0x70, 0x2d, 0x84, 0xa8, 0x5d, 0x3a, 0x18, 0x5c, 0x78, 0x71, 0xe2, 0xa7, 0x74,
	0x09, 0x2d, 0x51, 0xd9, 0x5f, 0xeb, 0x00, 0x52, 0x71, 0x91, 0x7e, 0xdd, 0x5c, 0xab, 0x2b, 0xf0,
	0x97, 0x89, 0x3b, 0x9f, 0x0b, 0xdf, 0x5c, 0x81, 0x44, 0x90, 0x83, 0x55, 0x90, 0x9e, 0x2e, 0xc2,
	0x50, 0xd9, 0x6f, 0x73, 0x5a, 0xc9, 0xd1, 0x73, 0x3e, 0xcd, 0xd2, 0xc3, 0x1b, 0x37, 0x08, 0x65,
	0xd7, 0x52, 0xe9, 0x6b, 0xf3, 0x32, 0x51, 0x62, 0x67, 0x71, 0xe6, 0x86, 0x23, 0xa4, 0xe6, 0x85,
	0x5e, 0x10, 0x9c, 0xb7, 0x00, 0xd4, 0x42, 0xce, 0xaa, 0xa9, 0xca, 0x41, 0x83, 0x5b, 0x14, 0x87,
	0xc1, 0x26, 0x55, 0xf8, 0x59, 0xe4, 0x8b, 0x5b, 0xd5, 0xfc, 0x5a, 0xbc, 0x44, 0x33, 0x51, 0x6d,
	0xbf, 0x41, 0x54, 0xd9, 0x15, 0x6c, 0x8f, 0x5c, 0x6f, 0x8a, 0x2d, 0x3e, 0x5e, 0x50, 0xfa, 0xbe,
	0x5e, 0xc4, 0xcc, 0xae, 0xea, 0x4b, 0xbb, 0x62, 0x9f, 0x00, 0xe8, 0xe4, 0x28, 0xf8, 0x5d, 0x68,
	0x79, 0xd2, 0x16, 0x8d, 0xe6, 0x7a, 0x21, 0xa3, 0x7a, 0xb5, 0x98, 0x4c, 0xa8, 0xb7, 0xe1, 0xb8,
	0xaa, 0x57, 0xec, 0xbf, 0x35, 0xe8, 0x73, 0x81, 0x1b, 0x14, 0x37, 0xe2, 0x7c, 0x2e, 0x8d, 0xe9,
	0xb4, 0x62, 0xa4, 0x70, 0x03, 0x58, 0x46, 0x2a, 0x0e, 0x1a, 0xca, 0xa2, 0x48, 0x7e, 0xb4, 0x98,
	0xe9, 0xad, 0xe5, 0x2e, 0x59, 0x94, 0xf2, 0x26, 0x1b, 0x6f, 0xb4, 0x49, 0x9c, 0x7a, 0xb1, 0x01,
	0xce, 0xdc, 0xfc, 0xc6, 0xdc, 0xb3, 0x07, 0x4f, 0x89, 0x7a, 0xaa, 0xb8, 0x9c, 0xa4, 0x70, 0xe4,
	0xdb, 0xc0, 0xf3, 0xe9, 0x05, 0xf2, 0x80, 0xd2, 0x71, 0xb4, 0x3a, 0xf6, 0x45, 0x30, 0x13, 0xe8,
	0xef, 0x6c, 0x3e, 0xca, 0x65, 0xb8, 0x11, 0x97, 0x21, 0x33, 0x4e, 0xb0, 0xf7, 0xa0, 0x79, 0x82,
	0xbe, 0x3b, 0xeb, 0xd0, 0x98, 0xf2, 0xdb, 0xde, 0x37, 0xd4, 0x9f, 0x8b, 0xdb, 0x5e, 0x0d, 0xe7,
	0xb1, 0xee, 0xf4, 0x28, 0x28, 0x7c, 0x74, 0xc3, 0x5e, 0x1d, 0xa5, 0xb7, 0x4a, 0x0e, 0xb1, 0x07,
	0xa4, 0xde, 0x86, 0xe6, 0x94, 0xbb, 0xbf, 0x43, 0xfd, 0x0d, 0x68, 0x4d, 0x47, 0x78, 0x6e, 0x7a,
	0x35, 0xb4, 0xd4, 0x5f, 0xe1, 0x0b, 0xfb, 0x36, 0xe9, 0x6c, 0xc1, 0xc6, 0xf4, 0x69, 0xe0, 0x25,
	0xf1, 0x58, 0x78, 0xa8, 0xb8, 0x09, 0xed, 0xe9, 0x33, 0x37, 0x52, 0xab, 0x1a, 0xf3, 0x60, 0xd3,
	0x9e, 0xb9, 0xd9, 0x98, 0x94, 0xfa, 0xb0, 0x3d, 0x1d, 0x97, 0x06, 0x68, 0x54, 0x95, 0xc4, 0xe3,
	0xd2, 0x50, 0x8c, 0xfe, 0xf7, 0x60, 0x73, 0x6a, 0xcd, 0xbe, 0xbd, 0xba, 0xb3, 0x0d, 0x9d, 0xa9,
	0x19, 0x69, 0x7b, 0x0d, 0xf6, 0x53, 0xd8, 0x5e, 0x1a, 0xa8, 0xd8, 0xf7, 0xac, 0x0d, 0x5d, 0xfa,
	0x29, 0xf9, 0x45, 0x37, 0x13, 0xa2, 0x76, 0x60, 0x7d, 0xaa, 0x2f, 0x16, 0x0c, 0xc7, 0xaf, 0x71,
	0x83, 0xd5, 0xeb, 0x91, 0x9d, 0x10, 0x86, 0xb4, 0x47, 0x49, 0x39, 0x0c, 0x43, 0x84, 0xba, 0x07,
	0x3b, 0xd3, 0xcb, 0xb4, 0x7c, 0xcf, 0x21, 0x26, 0x91, 0x49, 0xb4, 0x40, 0x97, 0x33, 0xc4, 0x8a,
	0xdb, 0x92, 0x7d, 0x76, 0x17, 0xbc, 0xdc, 0x31, 0x11, 0x9e, 0xe1, 0x68, 0x75, 0x37, 0xf2, 0x10,
	0x76, 0x2a, 0x37, 0x27, 0x3b, 0x78, 0x8d, 0xd7, 0x65, 0x90, 0x1a, 0xfb, 0x14, 0x33, 0x64, 0xcd,
	0x16, 0xec, 0xfb, 0x56, 0x86, 0x0c, 0xb8, 0x64, 0x91, 0x6b, 0xb4, 0x0b, 0x45, 0xa9, 0xb1, 0x43,
	0x2c, 0x25, 0xbb, 0x6b, 0xb0, 0x0f, 0x6c, 0xfd, 0x9c, 0x11, 0xcb, 0xbe, 0x48, 0x19, 0x36, 0xd2,
	0x49, 0x86, 0xc4, 0x1a, 0xfb, 0x39, 0xac, 0xd3, 0x63, 0x96, 0x3d, 0x26, 0xe5, 0x1d, 0xd8, 0x9a,
	0x2a, 0x81, 0xf3, 0x89, 0x1a, 0x59, 0x51, 0xb5, 0x0b, 0x90, 0x93, 0xce, 0x46, 0x18, 0x93, 0x5d,
	0xe8, 0xe5, 0xeb, 0x91, 0x7c, 0xeb, 0x7b, 0xb1, 0xac, 0xec, 0x1b, 0x58, 0xd3, 0xe3, 0x3d, 0x0b,
	0xad, 0x38, 0x3c, 0x8b, 0x33, 0x53, 0x65, 0x92, 0x70, 0x18, 0xf9, 0xa6, 0xc2, 0x24, 0xf2, 0x79,
	0x52, 0xae, 0xaf, 0xe7, 0x71, 0x41, 0x68, 0xa8, 0x5d, 0x63, 0x49, 0x17, 0x2a, 0x4d, 0x02, 0x2d,
	0x44, 0x5a, 0xec, 0x3f, 0xf8, 0x7e, 0xb5, 0xc6, 0x72, 0xf6, 0xaf, 0xba, 0x75, 0x3a, 0x0e, 0xa3,
	0x97, 0xf9, 0x2e, 0xe4, 0xc6, 0x50, 0xec, 0xf3, 0x38, 0xf6, 0x35, 0x49, 0x9b, 0x47, 0xd2, 0x91,
	0xeb, 0x0f, 0xf9, 0x10, 0xcd, 0x4b, 0x6b, 0x7a, 0xad, 0x25, 0x1a, 0xf8, 0x84, 0xdf, 0x95, 0x14,
	0x84, 0x19, 0x8b, 0xaf, 0x16, 0x22, 0xf2, 0xb4, 0x25, 0xf4, 0x63, 0x1f, 0xf6, 0x24, 0x67, 0x3c,
	0x73, 0xc3, 0xb0, 0xcc, 0x6b, 0xe5, 0x5a, 0x47, 0xc1, 0x75, 0x99, 0xb3, 0x86, 0xbd, 0x78, 0x20,
	0x39, 0x1c, 0x1b, 0x26, 0xce, 0xa3, 0x65, 0xee, 0x7a, 0x8e, 0x29, 0xcf, 0xdc, 0x19, 0x4e, 0xc1,
	0xd7, 0x49, 0x90, 0xbd, 0xd4, 0xbc, 0xb6, 0xf3, 0x36, 0x3c, 0x24, 0x4f, 0xce, 0xe6, 0x17, 0xde,
	0xfc, 0xd2, 0x9f, 0x0f, 0x5f, 0x08, 0x6f, 0x9a, 0x2e, 0x66, 0x5a, 0x62, 0x03, 0xbb, 0xea, 0xbe,
	0x85, 0x7d, 0xbc, 0x98, 0xe3, 0x88, 0x86, 0x65, 0xa1, 0xbb, 0x4d, 0x0f, 0x54, 0x05, 0x48, 0x8f,
	0xc9, 0xe8, 0xe7, 0xd8, 0x61, 0x3a, 0x79, 0x54, 0x86, 0x7e, 0xa8, 0x60, 0xd2, 0xde, 0x66, 0xee,
	0xfd, 0xe9, 0x30, 0x3e, 0x39, 0x8b, 0x6e, 0xdc, 0x30, 0xa0, 0x68, 0x6c, 0xb1, 0x8f, 0x65, 0xc1,
	0x9a, 0xd7, 0x06, 0xfb, 0xae, 0x95, 0x68, 0x74, 0x8c, 0x58, 0xf9, 0x39, 0x32, 0x82, 0xaa, 0xd6,
	0xf7, 0x56, 0xbf, 0x20, 0x4b, 0xcd, 0xec, 0x9c, 0xde, 0x85, 0xd4, 0x34, 0x8a, 0x42, 0x61, 0x7f,
	0x80, 0x07, 0xaf, 0x18, 0xf4, 0xd9, 0x6f, 0x09, 0xe3, 0x01, 0xdc, 0x9f, 0x8e, 0x83, 0xd9, 0x3c,
	0x14, 0xcb, 0x62, 0x88, 0x28, 0x63, 0x3f, 0x8c, 0x25, 0xf3, 0xb6, 0xc2, 0xad, 0x29, 0xee, 0x45,
	0x3c, 0x75, 0x03, 0x3f, 0xae, 0x70, 0xeb, 0xec, 0x9f, 0x35, 0x7c, 0x58, 0x96, 0xa6, 0x2c, 0xf6,
	0xf7, 0x1a, 0x19, 0x95, 0xa7, 0x9b, 0x02, 0x75, 0x2c, 0xc2, 0x60, 0x16, 0x64, 0xca, 0x9c, 0xec,
	0xfe, 0x76, 0xfc, 0x52, 0xea, 0xa8, 0x44, 0x93, 0xb3, 0x33, 0x96, 0xdc, 0x7d, 0xe8, 0xcb, 0x72,
	0xc6, 0x2a, 0x92, 0x04, 0x59, 0x79, 0x43, 0x59, 0x8b, 0xba, 0xf2, 0x0c, 0x43, 0x55, 0xad, 0xe2,
	0x34, 0xf1, 0x36, 0x76, 0xa6, 0x97, 0x78, 0x8f, 0x26, 0xa9, 0xad, 0xd1, 0x52, 0x50, 0x05, 0xdd,
	0x28, 0xac, 0x29, 0xab, 0xbf, 0xb0, 0xfc, 0x58, 0xc7, 0xfe, 0xda, 0xb1, 0x86, 0x5c, 0x7c, 0x80,
	0xdb, 0x4b, 0xbc, 0xb0, 0x1b, 0xab, 0xe6, 0x61, 0xfd, 0xed, 0xc3, 0x12, 0x64, 0x2e, 0xec, 0x54,
	0x1f, 0x6e, 0x4f, 0x56, 0x10, 0x09, 0xf2, 0xad, 0x15, 0xd3, 0xb2, 0xf5, 0x09, 0x82, 0x57, 0x15,
	0xd9, 0x97, 0xf6, 0x13, 0x5f, 0x39, 0xfb, 0x78, 0x99, 0x42, 0xe0, 0xab, 0x46, 0x71, 0xfd, 0xcc,
	0x2e, 0x8b, 0xb3, 0xdf, 0x2c, 0xbd, 0x3a, 0x14, 0xea, 0xcf, 0x56, 0x10, 0x09, 0xd8, 0x3c, 0x96,
	0x2a, 0x8f, 0x15, 0x5e, 0x55, 0xc2, 0xb6, 0x4c, 0x13, 0xae, 0xc2, 0xfd, 0xc8, 0x5e, 0x11, 0xa0,
	0x99, 0x65, 0xcc, 0x28, 0xcc, 0x2d, 0x31, 0x76, 0x59, 0x9a, 0xfb, 0x14, 0xce, 0x51, 0x85, 0x44,
	0x60, 0x03, 0x2b, 0x4d, 0xa5, 0x51, 0x91, 0x2f, 0x2b, 0x1c, 0x6d, 0xfc, 0x2a, 0xff, 0x8e, 0x7b,
	0xb5, 0xa6, 0x3e, 0xd2, 0x7e, 0xf4, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xc1, 0x9b, 0xf2,
	0xf0, 0x15, 0x00, 0x00,
}
